#!/usr/bin/env bash
set -o pipefail

REPO_DIR="${REPO_DIR:-/home/kxr/ZoeDepth}"
CONDA_SH="${CONDA_SH:-/home/kxr/miniconda3/etc/profile.d/conda.sh}"
CONDA_ENV="${CONDA_ENV:-zoe}"
LOG_FILE="${LOG_FILE:-${REPO_DIR}/logs/kitti_train_5ep_bs4.log}"
DONE_FILE="${DONE_FILE:-${REPO_DIR}/logs/kitti_train_5ep_bs4.done}"
FAIL_FILE="${FAIL_FILE:-${LOG_FILE%.log}.failed}"

mkdir -p "$(dirname "${LOG_FILE}")"
rm -f "${FAIL_FILE}"

{
  echo
  echo "===== KITTI TRAIN START $(date '+%F %T %Z') ====="
  echo "EPOCHS=${EPOCHS:-5} BS=${BS:-4} WORKERS=${WORKERS:-8} LR=${LR:-default}"
  echo "IMG_SIZE=${IMG_SIZE:-default} MIDAS_MODEL_TYPE=${MIDAS_MODEL_TYPE:-default} TRAIN_MIDAS=${TRAIN_MIDAS:-default}"
  echo "VALIDATE_EVERY=${VALIDATE_EVERY:-default} LOG_IMAGES_EVERY=${LOG_IMAGES_EVERY:-default} PRINT_LOSSES=${PRINT_LOSSES:-1} PREFETCH=${PREFETCH:-default}"
  echo "PIN_MEMORY=${PIN_MEMORY:-default} PERSISTENT_WORKERS=${PERSISTENT_WORKERS:-default} PREFETCH_FACTOR=${PREFETCH_FACTOR:-default}"
  echo "GRAD_ACCUM_STEPS=${GRAD_ACCUM_STEPS:-1} MEMORY_LOG_EVERY=${MEMORY_LOG_EVERY:-0} CHECKPOINT_EVERY=${CHECKPOINT_EVERY:-0}"
  echo "W_EDGE=${W_EDGE:-0} EDGE_IMAGE_WEIGHT=${EDGE_IMAGE_WEIGHT:-default} EDGE_DEPTH_WEIGHT=${EDGE_DEPTH_WEIGHT:-default} W_GRAD=${W_GRAD:-0}"
  echo "USE_BOUNDARY_REFINE=${USE_BOUNDARY_REFINE:-0} BOUNDARY_REFINE_CHANNELS=${BOUNDARY_REFINE_CHANNELS:-default} BOUNDARY_REFINE_SCALE=${BOUNDARY_REFINE_SCALE:-default} BOUNDARY_REFINE_MODE=${BOUNDARY_REFINE_MODE:-default} BOUNDARY_REFINE_USE_DA_PRIOR=${BOUNDARY_REFINE_USE_DA_PRIOR:-0}"
  echo "USE_DISCONTINUITY_BRANCH=${USE_DISCONTINUITY_BRANCH:-0} DISCONTINUITY_CHANNELS=${DISCONTINUITY_CHANNELS:-default} USE_DISCONTINUITY_TEMPERATURE=${USE_DISCONTINUITY_TEMPERATURE:-0} DISCONTINUITY_TEMPERATURE_SCALE=${DISCONTINUITY_TEMPERATURE_SCALE:-default}"
  echo "W_BOUNDARY_CLS=${W_BOUNDARY_CLS:-0} W_BOUNDARY_BAND=${W_BOUNDARY_BAND:-0} BOUNDARY_BAND_RADIUS=${BOUNDARY_BAND_RADIUS:-default} W_BOUNDARY_CONTRAST=${W_BOUNDARY_CONTRAST:-0} W_BOUNDARY_ALIGN=${W_BOUNDARY_ALIGN:-0} W_NONBOUNDARY_SMOOTH=${W_NONBOUNDARY_SMOOTH:-0} W_NONBOUNDARY_PRESERVE=${W_NONBOUNDARY_PRESERVE:-0} NONBOUNDARY_PRESERVE_RADIUS=${NONBOUNDARY_PRESERVE_RADIUS:-default} BOUNDARY_LOG_GRAD_THRESHOLD=${BOUNDARY_LOG_GRAD_THRESHOLD:-default}"
  echo "BOUNDARY_ALIGN_MAX_DISTANCE=${BOUNDARY_ALIGN_MAX_DISTANCE:-default} BOUNDARY_ALIGN_PRED_WEIGHT=${BOUNDARY_ALIGN_PRED_WEIGHT:-default} BOUNDARY_ALIGN_COVERAGE_WEIGHT=${BOUNDARY_ALIGN_COVERAGE_WEIGHT:-default}"
  echo "USE_FROZEN_DA_PRIOR=${USE_FROZEN_DA_PRIOR:-0} FROZEN_DA_MODEL=${FROZEN_DA_MODEL:-default} FROZEN_DA_FEATURE_CHANNELS=${FROZEN_DA_FEATURE_CHANNELS:-default} FROZEN_DA_INPUT_SIZE=${FROZEN_DA_INPUT_SIZE:-default} FROZEN_DA_FUSION_SCALE=${FROZEN_DA_FUSION_SCALE:-default} USE_FROZEN_DA_BOUNDARY_GATE=${USE_FROZEN_DA_BOUNDARY_GATE:-0} FROZEN_DA_MIN_GATE=${FROZEN_DA_MIN_GATE:-default}"
  echo "SKIP_NAN_BATCHES=${SKIP_NAN_BATCHES:-0}"
} | tee -a "${LOG_FILE}"

source "${CONDA_SH}"
conda activate "${CONDA_ENV}"
cd "${REPO_DIR}"

export LD_LIBRARY_PATH="/usr/lib/wsl/lib:${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH:-}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-max_split_size_mb:128}"

scripts/train_kitti.sh 2>&1 | tee -a "${LOG_FILE}"
status=${PIPESTATUS[0]}

if [[ "${status}" -eq 0 ]]; then
  touch "${DONE_FILE}"
  echo "===== KITTI TRAIN DONE $(date '+%F %T %Z') =====" | tee -a "${LOG_FILE}"
else
  echo "${status}" > "${FAIL_FILE}"
  echo "===== KITTI TRAIN FAILED status=${status} $(date '+%F %T %Z') =====" | tee -a "${LOG_FILE}"
fi

exit "${status}"
